export * from './Status/StatusFAQ';
export * from './Status/Status';
export * from './Status/CourseStatus';
export * from './FormControl/FormControl';
export * from './InputUpload/InputUpload';
export * from './RichEditor/RichEditor';
export * from './Table/CustomTable';
export * from './Table/TableHeader';
export * from './FreeTagInput/FreeTagInput';
export { CustomSwitch as Switch } from './Switch/Switch';
export * from './Modal/Modal';
export * from './TagsInput/TagsInput';
export * from './TabMenu/TabMenu';
export * from './TitleAndLanguage/TitleAndLanguage';
export { default as Title } from './Title/Title';
export * from './Video/Video';
export * from './ScreenLoading/ScreenLoading';
export * from './Button/BackButton';
export * from './GroupButton/GroupButtonSearch';
export * from './InputSelect/InputSelect';
export * from './InputNumber/InputNumber';
export * from './Tooltip/Tooltip';
export * from './SecurityArea/SecurityArea';
export * from './EllipsisSelect/EllipsisSelect';
